### ISSUE TITLE
LC does not support double precision watchpoints

### ISSUE THREAD

**Issue by SpaceSteve121** [nasa/LC#3] opened 2021-07-29 17:56 UTC
LC does not currently support [defining a watchpoint](https://github.com/nasa/LC/blob/82bd57b541f313fba238ba3f191dda607b097656/fsw/src/lc_tbl.h) for a double precision value. Doubles are commonly used in GNC applications, and it would be helpful for LC to support monitoring those telemetry points, rather than requiring the upstream app to provide special telemetry for LC to monitor.

**Comment by skliper** [comment] 2022-04-22 18:56
Duplicate of #5

**Closed by skliper** 2022-04-22 18:56 UTC
